Use node 16
Think this is now required to avoid this Heroku error preventing deployment:

```

       Resolving node version >=14.0.0 <17.0.0...
       Error: Unknown error installing ">=14.0.0 <17.0.0" of node
-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       Some possible problems:

       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
```